Repository one-short-rib/nagano-cake-ec, pull requests merged in 2020-05, with the labels that each got.

#10 Generating item and order models
  app/assets/images/sample.jpg
  app/models/item.rb
  app/models/order.rb
  db/migrate/20200514093045_create_items.rb
  db/migrate/20200514093456_create_orders.rb
  db/schema.rb
  test/fixtures/items.yml
  test/fixtures/orders.yml
  test/models/item_test.rb
  test/models/order_test.rb
Labels: enhancement

#19 Add 4 sample images
  app/assets/images/sample1.jpg
  app/assets/images/sample2.jpg
  app/assets/images/sample3.jpg
  app/assets/images/sample4.jpg
Labels: enhancement

#16 Readme by yoshi
  README.md
Labels: enhancement

#22 Modifying test
  test/fixtures/admins.yml
  test/fixtures/cart_items.yml
  test/fixtures/genres.yml
  test/fixtures/items.yml
  test/fixtures/members.yml
  test/fixtures/order_items.yml
  test/fixtures/orders.yml
  test/fixtures/ships.yml
Labels: documentation

#34 Feature cart items
  app/assets/javascripts/member/cart_items.coffee
  app/assets/stylesheets/member/cart_items.scss
  app/controllers/member/cart_items_controller.rb
  app/helpers/member/cart_items_helper.rb
  app/models/cart_item.rb
  app/views/member/cart_items/_cart_item.html.erb
  app/views/member/cart_items/index.html.erb
  test/controllers/member/cart_items_controller_test.rb
Labels: enhancement

#35 add__admin_member,admin_genre
  app/assets/javascripts/admin/genres.coffee
  app/assets/javascripts/admin/homes.coffee
  app/assets/javascripts/admin/members.coffee
  app/assets/stylesheets/admin/genres.scss
  app/assets/stylesheets/admin/homes.scss
  app/assets/stylesheets/admin/members.scss
  app/controllers/admin/genres_controller.rb
  app/controllers/admin/homes_controller.rb
  app/controllers/admin/members_controller.rb
  app/helpers/admin/genres_helper.rb
  app/helpers/admin/homes_helper.rb
  app/helpers/admin/members_helper.rb
  app/views/admin/genres/edit.html.erb
  app/views/admin/genres/index.html.erb
  app/views/admin/homes/top.html.erb
  app/views/admin/members/edit.html.erb
  app/views/admin/members/index.html.erb
  app/views/admin/members/show.html.erb
  test/controllers/admin/genres_controller_test.rb
  test/controllers/admin/homes_controller_test.rb
  test/controllers/admin/members_controller_test.rb
Labels: enhancement, help wanted

#53 Feature home controller
  app/controllers/homes_controller.rb
  app/views/homes/top.html.erb
  test/controllers/homes_controller_test.rb
  test/controllers/member/members_controller_test.rb
  test/controllers/member/ships_controller_test.rb
  test/integration/home_test.rb
Labels: enhancement

#51 Feature member order controller
  Gemfile
  Gemfile.lock
  app/controllers/member/orders_controller.rb
  app/helpers/member/orders_helper.rb
  app/models/order.rb
  app/views/admin/items/index.html.erb
  app/views/items/_item_contents.html.erb
  app/views/member/orders/_billing_info.html.erb
  app/views/member/orders/_confirmation_button.html.erb
  app/views/member/orders/_order_contents.html.erb
  app/views/member/orders/_order_info.html.erb
  app/views/member/orders/_orders_list.html.erb
  app/views/member/orders/_payment_method_buttons.html.erb
  app/views/member/orders/confirm.html.erb
  app/views/member/orders/index.html.erb
  app/views/member/orders/new.html.erb
  app/views/member/orders/show.html.erb
  app/views/member/orders/thanks.html.erb
  app/views/member/ships/_ship_buttons.html.erb
  test/controllers/admin/items_controller_test.rb
  test/controllers/admin/order_items_controller_test.rb
  test/controllers/admin/orders_controller_test.rb
  test/controllers/member/cart_items_controller_test.rb
  test/controllers/member/members_controller_test.rb
  test/controllers/member/orders_controller_test.rb
  test/controllers/member/ships_controller_test.rb
  test/fixtures/cart_items.yml
  test/fixtures/members.yml
  test/fixtures/order_items.yml
  test/fixtures/orders.yml
  test/fixtures/ships.yml
  test/integration/member_order_interface_test.rb
  test/models/cart_item_test.rb
  test/models/order_item_test.rb
  test/models/order_test.rb
  test/models/ship_test.rb
Labels: enhancement

#65 Test
  test/fixtures/admins.yml
  test/models/admin_test.rb
  test/models/member_test.rb
  test/models/order_test.rb
  test/models/ship_test.rb
Labels: テスト用

#66 Modify item interface
  app/models/item.rb
  app/models/member.rb
  app/views/items/_cart_button.html.erb
  app/views/items/_item_index.html.erb
  app/views/items/_item_show.html.erb
  app/views/items/show.html.erb
  test/models/item_test.rb
Labels: 追加or修正

#68 Fix home interface
  app/views/homes/about.html.erb
  app/views/homes/top.html.erb
  test/integration/home_test.rb
Labels: 追加or修正

#75 Fix order interface
  app/controllers/member/orders_controller.rb
  app/helpers/member/orders_helper.rb
  app/views/items/_item_contents.html.erb
  app/views/member/orders/_billing_info.html.erb
  app/views/member/orders/_order_contents.html.erb
  app/views/member/orders/_order_info.html.erb
  app/views/member/orders/_orders_list.html.erb
  app/views/member/orders/confirm.html.erb
  app/views/member/orders/index.html.erb
  app/views/member/orders/show.html.erb
  test/controllers/member/orders_controller_test.rb
  test/fixtures/items.yml
  test/fixtures/order_items.yml
  test/fixtures/orders.yml
  test/integration/member_order_interface_test.rb
Labels: 追加or修正

#77 Hotfix test
  app/controllers/member/orders_controller.rb
  app/helpers/member/orders_helper.rb
  app/models/order.rb
  app/views/items/_item_contents.html.erb
  app/views/member/orders/_billing_info.html.erb
  app/views/member/orders/_confirmation_button.html.erb
  app/views/member/orders/confirm.html.erb
  test/integration/header_test.rb
Labels: バグ修正, 追加or修正

#81 Hotfix total helpers
  app/controllers/homes_controller.rb
  app/controllers/member/orders_controller.rb
  app/helpers/admin/orders_helper.rb
  app/helpers/application_helper.rb
  app/helpers/member/cart_items_helper.rb
  app/helpers/member/orders_helper.rb
  app/models/cart_item.rb
  app/models/order.rb
  app/views/admin/orders/show.html.erb
  app/views/member/cart_items/index.html.erb
  test/controllers/admin/genres_controller_test.rb
  test/controllers/admin/homes_controller_test.rb
  test/controllers/admin/items_controller_test.rb
  test/controllers/admin/members_controller_test.rb
  test/controllers/admin/orders_controller_test.rb
  test/controllers/member/orders_controller_test.rb
  test/integration/admin_order_interface_test.rb
Labels: issue解決, 要チェック

#85 Add css for ships
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/member/members.scss
  app/assets/stylesheets/member/ships.scss
  app/views/member/ships/_ship.html.erb
  app/views/member/ships/edit.html.erb
  app/views/member/ships/index.html.erb
Labels: 追加or修正

#94 Hotfix order create action
  app/controllers/member/orders_controller.rb
  app/models/order.rb
  app/views/member/orders/_confirmation_button.html.erb
  app/views/member/orders/confirm.html.erb
  test/integration/member_order_interface_test.rb
Labels: 追加or修正

#96 Feature layout member order
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/member/members.scss
  app/assets/stylesheets/member/orders.scss
  app/assets/stylesheets/member/ships.scss
  app/helpers/application_helper.rb
  app/views/items/_item_contents.html.erb
  app/views/layouts/application.html.erb
  app/views/member/orders/_billing_info.html.erb
  app/views/member/orders/_order_contents.html.erb
  app/views/member/orders/_order_info.html.erb
  app/views/member/orders/_orders_list.html.erb
  app/views/member/orders/_payment_method_buttons.html.erb
  app/views/member/orders/confirm.html.erb
  app/views/member/orders/index.html.erb
  app/views/member/orders/new.html.erb
  app/views/member/orders/show.html.erb
  app/views/member/orders/thanks.html.erb
  app/views/member/ships/_ship_buttons.html.erb
  test/integration/admin_order_interface_test.rb
  test/integration/home_test.rb
  test/integration/item_interface_test.rb
  test/integration/member_order_interface_test.rb
Labels: 要チェック, 追加or修正

#98 Fix bugs
  app/views/admin/orders/show.html.erb
  app/views/member/orders/confirm.html.erb
Labels: バグ修正

#114 Feature member order flash
  app/controllers/member/orders_controller.rb
  app/models/order.rb
  test/integration/member_order_interface_test.rb
Labels: 追加or修正

#121 Hotfix whole site
  app/assets/stylesheets/application.scss
  app/views/admin/items/edit.html.erb
  app/views/homes/top.html.erb
  app/views/layouts/_header.html.erb
  app/views/layouts/application.html.erb
  app/views/member/ships/_ship_buttons.html.erb
  test/integration/home_test.rb
Labels: 追加or修正

#131 Modify footer
  app/assets/images/no_image2.jpg
  app/assets/stylesheets/application.scss
  app/views/layouts/_footer.html.erb
  app/views/layouts/application.html.erb
  app/views/member/ships/_ship_buttons.html.erb
  test/fixtures/items.yml
Labels: 追加or修正

#133 Feature password reset
  app/controllers/member/members_controller.rb
  app/controllers/members/registrations_controller.rb
  app/views/items/_item_index.html.erb
  app/views/items/_item_show.html.erb
  app/views/member/cart_items/_cart_item.html.erb
  app/views/member/members/show.html.erb
  app/views/members/registrations/edit.html.erb
  config/routes.rb
Labels: issue解決, 追加or修正

#132 Modify test
  test/controllers/admin/genres_controller_test.rb
  test/controllers/admin/homes_controller_test.rb
  test/controllers/admin/items_controller_test.rb
  test/controllers/admin/members_controller_test.rb
  test/controllers/admin/orders_controller_test.rb
  test/controllers/member/members_controller_test.rb
  test/integration/admin_order_interface_test.rb
Labels: テスト用

#143 Fix members/orders/new
  app/views/member/ships/_ship_buttons.html.erb
Labels: バグ修正

#150 Feature ajax cart
  app/assets/stylesheets/application.scss
  app/controllers/member/cart_items_controller.rb
  app/views/layouts/_flash.html.erb
  app/views/layouts/application.html.erb
  app/views/member/cart_items/_cart_item.html.erb
  app/views/member/cart_items/destroy.js.erb
  app/views/member/cart_items/index.html.erb
  app/views/member/cart_items/update.js.erb
  app/views/member/ships/_ship_buttons.html.erb
Labels: issue解決, 追加or修正

#156 Fix cart_item controller
  app/controllers/member/cart_items_controller.rb
Labels: バグ修正

#161 Hotfix genred items
  app/controllers/homes_controller.rb
  app/controllers/items_controller.rb
  app/models/item.rb
Labels: バグ修正

#164 Hotfix genreditem
  app/controllers/admin/genres_controller.rb
  app/controllers/admin/items_controller.rb
  app/controllers/items_controller.rb
  app/models/item.rb
Labels: バグ修正
